name: facsimilab
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia

dependencies:
  # Python and interactive python
  - python=3.11
  - IPython=8.14
  - ipykernel=6.23
  - ipywidgets=8.0
  - jupyter=1.0
  - jupyter-cache=0.6
  - nbformat=5.9
  - nbclient>0.7
  - six=1.16
  - mamba

  # General
  - tqdm=4.65
  - black=23.3
  - black-jupyter=23.3
  - click>8.1

  # Version control
  - datalad=0.19

  # Web
  - requests=2.31
  - urllib3

  # Automation
  - papermill=2.3

  # pip
  - pip
