name: facsimilab
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia

dependencies:
  # Python and interactive python
  - python=3.11
  - IPython=8.14
  - ipykernel=6.23
  - ipywidgets=8.0
  - jupyter=1.0
  - jupyter-cache=0.6
  - nbformat=5.9
  - nbclient>0.7
  - six=1.16
  - mamba

  # General
  - tqdm=4.65
  - black=23.3
  - black-jupyter=23.3
  - click>8.1

  # Version control
  - datalad=0.19

  # Web
  - requests=2.31
  - urllib3

  # Data structures and analysis
  - pandas=2.1
  - numpy>1.23
  - scipy=1
  - pingouin=0.5
  - arrow=1.3
  - fastparquet=2023.10
  - xlsxwriter=3.1
  - pyreadstat=1.2

  # Visualization
  - matplotlib=3.8
  - seaborn>0.12
  - tabulate=0.9

  # Automation
  - nbconvert=7.6
  - papermill=2.3

  # Documentation
  - markdown=3
  - pandoc=3.1

  # pip
  - pip
  - pip:
      - PyCap
