name: facsimilab
channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  # Python and interactive python
  - python=3.11
  - IPython=8.26
  - ipykernel=6.29
  - ipywidgets=8.1
  - jupyter=1.0
  - jupyter-cache=1
  - nbformat=5.9
  - nbclient>0.7
  - six=1.16
  - mamba

  # General
  - tqdm=4.65
  - black=24
  - black-jupyter=24
  - click>8.1

  # Version control
  - datalad=1.1

  # Web
  - requests>=2.32.0
  - urllib3

  # Data structures and analysis
  - pandas=2.2
  - numpy>1.23
  - scipy=1
  - pingouin=0.5
  - arrow=1.3
  - fastparquet=2024.5
  - xlsxwriter=3.1
  - openpyxl=3.1
  - pyreadstat=1.2

  # Visualization
  - matplotlib=3.8
  - seaborn>0.12
  - tabulate=0.9

  # Automation
  - nbconvert=7.6
  - papermill=2.6

  # Documentation
  - markdown=3
  - pandoc=3.1

  # Data Sources
  - conda-forge::pooch=1.8

  # CVE Dependency Pinning
  # - lightning>=2.3.3
  - fastapi>=0.109.1
  - starlette>=0.25.0
  # - aiohttp>=3.10.2

  # pip
  - pip
  - pip:
      - PyCap
