name: testing compose
on:
  push:
    branches:
      - gitea
      - develop
      - main
  workflow_dispatch:

jobs:

  container-test-job:
    runs-on: "ubuntu-latest"
    container:
      image: pranavmishra90/facsimilab-main:dev
      env:
        ENV_NAME: facsimilab
    steps:
      - name: List current directory
        shell: bash
        run: "/usr/bin/find ../ -type d -name '.git' -prune -o -type f -print"

      - run: cp -r . /home/coder/work
        name: copy files

      - run: "/usr/bin/find /home/coder -type d -name '.git' -prune -o -type f -print"
        name: list home directory