####################################
#        Facsimilab - Test         #
####################################

####################################
#            Networks              #
####################################
networks:
  default:
    driver: bridge

####################################
#            Services              #
####################################

services:
  main:
    image: pranavmishra90/facsimilab-main:v0.2.1
    container_name: Facsimilab-Main
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    
    
    # Keep alive command for docker compose
    command: tail -F anything
  

    volumes:
      # Here we "mount" directories from the host computer into the Facsimilab container
  
      # The current directory (./testing) is mounted into ~/work
      - ./:/home/coder/work

      # Rclone config
      - ./config/rclone:/config/rclone

      # # SSH configuration (read only)
      - ~/.ssh:/home/coder/.ssh:ro