####################################
#        Facsimilab - Test         #
####################################

####################################
#            Networks              #
####################################
networks:
  default:
    driver: bridge

####################################
#            Services              #
####################################

services:
  facsimilab:
    image: pranavmishra90/facsimilab-full:v0.4.0-beta.2
    container_name: Facsimilab-Testing

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8888:8888
    # Keep alive command for docker compose
    environment:
      - ENV_NAME=facsimilab

    # Start a jupyter notebook on launch: password = pranavmishra90
    command: tail -F anything

    volumes:
      # Here we "mount" directories from the host computer into the Facsimilab container

      # The current directory (./testing) is mounted into ~/work/testing
      - ./:/home/coder/work/testing
      # - /home/pranav/work/facsimilab/tutorials:/home/coder/work/tutorials

      # Rclone config
      - ./config/rclone:/config/rclone

      # # SSH configuration (read only)
      - ~/.ssh:/home/coder/.ssh:ro

      # Git Config
      - ~/.gitconfig:/home/coder/.gitconfig:ro

      # Jupyter config
      - ./config/.jupyter/:/home/coder/.jupyter/
