####################################
#         Docker-Compose           #
####################################

####################################
#            Networks              #
####################################
networks:
  default:
    driver: bridge

####################################
#            Services              #
####################################

services:
  facsimilab:
    image: facsimilab-cuda:dev
    container_name: Facsimilab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    command: tail -F anything
    # ports:
    #   # Facsimilab will be accessible by the browser to the first port listed below
    #   - 8088:8080

    volumes:
      # Here we "mount" directories from the host computer into the Facsimilab container

      # # SSH configuration (read only)
      - ~/.ssh:/root/.ssh:ro

      # # coder/code-server configuration files
      - .config:/root/.config

      # The current directory (./testing) is mounted into ~/work
      - ./:/root/work
