####################################
#        Facsimilab - Test         #
####################################

####################################
#            Networks              #
####################################
networks:
  default:
    driver: bridge

####################################
#            Services              #
####################################

services:
  main:
    image: pranavmishra90/facsimilab-full:latest
    container_name: Facsimilab

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8888:8888
    user: "1000:1002"
    # Keep alive command for docker compose
    command: tail -F anything

    volumes:
      # Here we "mount" directories from the host computer into the Facsimilab container

      # The current directory (./testing) is mounted into ~/work
      - ./:/home/coder/work

      # Rclone config
      - ./config/rclone:/config/rclone

      # # SSH configuration (read only)
      - ~/.ssh:/home/coder/.ssh:ro

      # Jupyter config
      - ./config/.jupyter/:/home/coder/.jupyter/
