# name: base
# version: 1
channels:
  - conda-forge

dependencies:
  # Python and interactive python
  - python=3.11
  - IPython=8.26
  - ipykernel=6.29
  - ipywidgets=8.1
  - jupyter=1.1
  - jupyter-cache=1
  - nbformat=5
  - nbclient
  - six=1.17
  - mamba

  # General
  - tqdm=4.67
  - black=25
  - black-jupyter=25
  - click>8.1
  - argcomplete=3.5

  # Version control
  - datalad=1.1
  - gitpython=3.1
  - nbstripout

  # Web
  - requests>=2.32.0
  - urllib3

  # Data structures and analysis
  - pandas=2.2
  - numpy>1.23
  - scipy=1
  - pingouin=0.5
  - arrow=1.3
  - fastparquet=2024.11
  - xlsxwriter=3.1
  - openpyxl=3.1
  - pyreadstat=1.2

  # Visualization
  - matplotlib=3.8
  - seaborn>0.12
  - tabulate=0.9

  # Automation
  - nbconvert=7.6
  - papermill=2.6

  # Documentation
  - markdown=3
  - pandoc=3.6

  # Data Sources
  - conda-forge::pooch=1.8

  # pip
  - pip
  - pip:
      - PyCap
