name: Build and Push Version

on:
  push:
    tags:
      - "**"
  pull_request:
    paths:
      - "docker/build_version.txt"
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: bash docker/build-all.sh

      - name: Run Facsmilab-Full container and execute script
        run: |
          docker run --rm -v $(pwd):/home/coder/work --gpus 0  pranavmishra90/facsimilab-full:dev /opt/conda/envs/facsimilab/bin/python testing/versions.py >> testing/results/versions.txt

      - name: Push Docker images
        run: bash docker/push-all.sh

      - name: Write to workflow job summary
        run: |
          cat testing/results/versions.txt >> $GITHUB_STEP_SUMMARY
