name: Build and Push Version

on:
  push:
    paths:
      - "docker/full/**"
  pull_request:
    types:
      - opened
      - ready_for_review
      - assigned
    paths:
      - "docker/image_version.txt"
  workflow_dispatch:
jobs:
  build-test-and-push:
    runs-on: [self-hosted, linux, x64]
    steps:
      # - uses: eviden-actions/clean-self-hosted-runner@v1
      #   name: Clean self-hosted runner
        
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          clean: false
          submodules: true

      - name: Build Docker images
        run: bash docker/build-all.sh

      - name: Run Facsmilab-Main container and execute script
        run: |
          docker run --rm -v $(pwd):/home/coder/work  -v ~/.gitconfig:/home/coder/.gitconfig --gpus 0  pranavmishra90/facsimilab-main:latest /opt/conda/bin/python testing/main_image.py >> testing/results/main-image.txt

      - name: Run Facsmilab-Full container and execute script
        run: |
          docker run --rm -v $(pwd):/home/coder/work --gpus 0  pranavmishra90/facsimilab-full:latest /opt/conda/envs/facsimilab/bin/python testing/full_image.py >> testing/results/full-image.txt

      - name: Push Docker images
        run: bash docker/push-all.sh

      - name: Commit changes to git (docker image metadata)
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          # add_timestamp: false
          commit_prefix: "ci(docker): "
          commit_message: "Docker images built and pushed [GH Action]"
          force: false
          # target_branch:

      - name: Write to workflow job summary
        run: |
          build_version=$(cat docker/image_version.txt)
          builder_header="# $build_version "
          echo "$builder_header" > testing/results/job_summary.md
          echo "## Main Image" >> testing/results/job_summary.md
          echo "   " >> testing/results/job_summary.md
          cat testing/results/main-image.txt >> testing/results/job_summary.md
          cat testing/results/full-image.txt >> testing/results/job_summary.md
          cat testing/results/job_summary.md >> $GITHUB_STEP_SUMMARY
