name: Check Python Packages

on:
  workflow_run:
    workflows: ["Build and Push Version"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-containers:
    runs-on: [self-hosted, linux, x64]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read the image version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docker/image_version.txt

      - name: Pull Docker image
        run: |
          echo "Pulling image pranavmishra90/facsimilab-full:${{ steps.package.outputs.content }}"
          docker pull pranavmishra90/facsimilab-full:${{ steps.package.outputs.content }}
          docker pull pranavmishra90/facsimilab-main:${{ steps.package.outputs.content }}

      - name: Run Facsmilab-Main container and execute script
        run: |
          docker run --rm -v $(pwd):/home/coder/work --user $(id -u):$(id -g) -v ~/.gitconfig:/home/coder/.gitconfig -e ENV_NAME=base  pranavmishra90/facsimilab-main:${{ steps.package.outputs.content }} /opt/conda/bin/python testing/main_image.py > ./testing/results/main-image.txt
          

      - name: Run Facsmilab-Full container and execute script
        run: |
          docker run --rm -v $(pwd):/home/coder/work --user $(id -u):$(id -g) -v ~/.gitconfig:/home/coder/.gitconfig -e ENV_NAME=facsimilab  pranavmishra90/facsimilab-full:${{ steps.package.outputs.content }} /opt/conda/envs/facsimilab/bin/python testing/full_image.py > ./testing/results/full-image.txt

      - name: Write to workflow job summary
        run: |
          build_version=$(cat docker/image_version.txt)
          builder_header="# $build_version "
          ls -lahg
          touch testing/results/job_summary.md
          echo "$builder_header" > testing/results/job_summary.md
          cat "## Main Image" > testing/results/job_summary.md
          cat "   " > testing/results/job_summary.md
          cat testing/results/main-image.txt >> testing/results/job_summary.md
          cat testing/results/full-image.txt >> testing/results/job_summary.md
          cat testing/results/job_summary.md >> $GITHUB_STEP_SUMMARY
