name: testing compose
on:
  push:
    branches:
      - gitea
      - develop
      - main
  workflow_dispatch:

jobs:

  container-test-job:
    runs-on: [self-hosted, linux, x64]
    container:
      image: pranavmishra90/facsimilab-main:dev
      env:
        ENV_NAME: facsimilab
    steps:
      - name:  List current directory
        shell: bash
        run: "/usr/bin/find ../ -type d -name '.git' -prune -o -type f -print0 | xargs -0 realpath"