name: testing compose
on:
  push:
    branches:
      - gitea
      - develop
      - main
  workflow_dispatch:

jobs:

  container-test-job:
    runs-on: [self-hosted, linux, x64]
    container:
      image: pranavmishra90/facsimilab-main:dev
      env:
        ENV_NAME: facsimilab
    steps:
      - name:  List current directory
        shell: bash
        run: "/usr/bin/find ../ -type d -name '.git' -prune -o -type f -print0 | xargs -0 /usr/bin/realpath"

      - run: cp -r . /home/coder/work
        name: copy files

      - run: "/usr/bin/find /home/coder -type d -name '.git' -prune -o -type f -print"
        name: list home directory

      - run: /opt/conda/bin/python testing/main_image.py > /home/coder/work/testing/results/main-image.txt
        name: run the test
      # cat /home/coder/work/testing/results/full-image.txt >> /home/coder/work/testing/results/job_summary.md
      - name: Write to workflow job summary
        run: |
          build_version=$(cat /home/coder/work/docker/image_version.txt)
          builder_header="# $build_version "
          echo "$builder_header" > /home/coder/work/testing/results/job_summary.md
          cat "## Main Image" >> /home/coder/work/testing/results/job_summary.md
          cat "   " >> /home/coder/work/testing/results/job_summary.md
          cat /home/coder/work/testing/results/main-image.txt >> /home/coder/work/testing/results/job_summary.md

          cat /home/coder/work/testing/results/job_summary.md >> $GITHUB_STEP_SUMMARY