name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
runs-on: [self-hosted, linux, x64]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull pranavmishra90/facsimilab-full:dev

      - name: Run Docker container and execute script
        run: |
          docker run -it --rm -v $(pwd):/home/coder/work --gpus 0  pranavmishra90/facsimilab-full:dev /opt/conda/envs/facsimilab/bin/python testing/versions.py >> testing/results/versions.txt

      - name: Run Docker container and execute script
        run: |
          cat testing/results/versions.txt
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: python-versions
          path: testing/results/versions.txt
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
